name: Deploy no Fly.io

on:
  push:
    branches:
      - main  # Faz o deploy quando há push na branch main

jobs:
  deploy:
    name: Deploy para Fly.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy para Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
